name: Build and Test

on:
  workflow_call:
    inputs:
      solution-path:
        required: true
        type: string
      so:
        required: true
        type: string


jobs:
  build-and-test:
    runs-on: ${{ inputs.so }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore Solution
      run: dotnet restore ${{ inputs.solution-path }}
    
    - name: Build Solution
      run: dotnet build --no-restore ${{ inputs.solution-path }}

    - name: Run Test
      run: dotnet test ${{ inputs.solution-path }}
