name: Build and Test

on:
  push:
    branches:
      - '**'

jobs:
  restore-build-dima:
    uses: ./.github/workflows/build-and-test.yml
    with:
<<<<<<< Updated upstream
      solution-path: ./bugs/
=======
      solution-path: ./bugs/Dima.sln
      so: windows-latest
>>>>>>> Stashed changes

  restore-build-test-balta:
    uses: ./.github/workflows/build-and-test.yml
    with:
<<<<<<< Updated upstream
      solution-path: ./unit-tests/
=======
      solution-path: ./unit-tests/Balta.sln
      so: ubuntu-latest
>>>>>>> Stashed changes
