name: Build and Test

on:
  push:
    branches:
      - '**'

jobs:
  restore-build-dima:
    uses: ./.github/workflows/restore-build.yml
    with:
      solution-path: ./bugs/

  restore-build-test-balta:
    uses: ./.github/workflows/restore-build-test.yml
    with:
      solution-path: ./unit-tests/