name: CI pipeline

on:
  push:
    branches:
      - '**'

jobs:
  dima:
    uses: ./.github/workflows/build-and-test.yml
    with:
      solution-path: ./bugs/Dima.sln


  balta:
    uses: ./.github/workflows/build-and-test.yml
    with:
      solution-path: ./unit-tests/Balta.sln
